### ISSUE TITLE
How to setup emmet-ls on native built-in lsp client in neovim?

### ISSUE THREAD

**Issue by RealYukiSan** [aca/emmet-ls#75]
I tried setup emmet-ls using the following configuration:
ftplugin/html.lua
```lua
local root_files = {
  'index.html'
}

local paths = vim.fs.find(root_files, { stop = vim.env.HOME })
local root_dir = vim.fs.dirname(paths[1])
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

if root_dir then
	vim.lsp.start({
		name = 'web-lsp',
		filetypes = { 'html', 'css', 'javascript' },
		cmd = {'emmet-ls'},
		capabilities = capabilities,
		root_dir = root_dir
	})
end
```

but it didn't work and instead show message: `Client 1 quit with exit code 1 and signal 0`

LSP log:
```
/usr/lib/node_modules/emmet-ls/node_modules/vscode-languageserver/lib/node/main.js:185
        throw new Error('Connection input stream is not set. ' + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (/usr/lib/node_modules/emmet-ls/node_modules/vscode-languageserver/lib/node/main.js:185:15)
    at createConnection (/usr/lib/node_modules/emmet-ls/node_modules/vscode-languageserver/lib/node/main.js:132:12)
    at Object.<anonymous> (/usr/lib/node_modules/emmet-ls/out/server.js:7:48)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1
```

**Comment by RealYukiSan** [comment]
my bad not take a look at [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/9553725789be682ecd945a527ec552e489ea8534/lua/lspconfig/server_configurations/emmet_ls.lua#L4)

**Comment by RealYukiSan** [comment]
hmm but still not working, I've confirm that the LSP attached by `:lua = vim.lsp.get_active_clients()` and `:lua = vim.cmd(string.format('tabnew %s', vim.lsp.get_log_path()))` but it not do anything when I start typing like `h1*5`

**Comment by RealYukiSan** [comment]
my current `ftplugin/html.lua`:
```lua
local root_files = {
  'index.html'
}

local paths = vim.fs.find(root_files, { stop = vim.env.HOME })
local root_dir = vim.fs.dirname(paths[1])
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

if root_dir then
	vim.lsp.start({
		name = 'web-lsp',
		filetypes = { 'html', 'css', 'javascript' },
		cmd = {'emmet-ls', '--stdio'},
		capabilities = capabilities,
		root_dir = root_dir
	})
end
```

**Comment by RealYukiSan** [comment]
Looks like emmet_ls not compatible with omnifunc, using nvim-cmp works great
